### PR TITLE
Aw station methods

### PR DESCRIPTION
**Pull request by wlffann**
@Sh1pley @Laszlo-JFLMTCO @MarisaMBurton 

Here are my three methods. I modeled them after Jesse's code which looks great! These should be able to merge straight into the branch.

Thanks!

### CODE REVIEW

**Comment by Laszlo-JFLMTCO** [comment]
@wlffann @Sh1pley @MarisaMBurton 
From my side these methods from Annie look great! I am OK to pull them into the CRUD_stations branch.

**Comment by Sh1pley** [comment]
@wlffann Great work! This is all coming together so nicely.

**Comment by Laszlo-JFLMTCO** [comment]
Looking good with the latest updates! Let's merge it! :-)

**Comment by wlffann** [comment]
Thanks, guys!

**Pull request merged**
