### PR TITLE
Shipley i3

### PR DESCRIPTION
**Pull request by Sh1pley**
@Laszlo-JFLMTCO 
@wlffann 
@MarisaMBurton 

Please call me on my nonsense if these are not the requested actions.. my brain has led me to believe this is the correct offering for these methods. All input is graciously appreciated. I have also moved these waffle items into the Refactor phase within waffle. 

You guys are awesome!

### CODE REVIEW

**Comment by wlffann** [comment]
The code looks great! I think that we can merge this into master, but I think we were hoping to merge it into CRUD_stations instead in order to finish out that branch before we merge anything into master

**Comment by Laszlo-JFLMTCO** [comment]
I agree with @wlffann that we wanted to merge all changes into CRUD-stations branch instead of Master. Also a general comment based on the ActiveRecord evaluation rubric of the project:
"2: Limited use of ActiveRecord methods (for exxample: frequent use of .all followed by data manipulation using Ruby where other ActiveRecord methods would be more appropriate)."
I would suggest to refactor the find_fewest_bikes function:
current code:
```
def self.find_fewest_bikes
  Station.all.map do |station|
    station.dock_count
  end.sort.first
end
```
Proposed code:
```
def self.find_fewest_bikes
  Station.minimum("dock_count")
end
```

Please let me know what you think.

**Comment by Sh1pley** [comment]
@wlffann @Laszlo-JFLMTCO @MarisaMBurton 

adds my methods into yours, still needs some refactoring and tests.

**Comment by wlffann** [comment]
@Sh1pley, thanks for updating these files! I'm ready for our first merge on this branch

**Comment by Laszlo-JFLMTCO** [comment]
Thank you Sir! Just as discussed let's merge it and double check as part of the refactoring effort.

**Comment by ghost** [comment]
i endorse the merging of this branch

**Pull request merged**
